@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam DefaultTextAlignment left
skinparam classAttributeFontColor white
skinparam classAttributeIconSize 0

show members

package Model {
class Asset {
    -assetName: String
    --
    +{static} of(String): Asset
}

hide empty attributes
hide empty methods
class Person

class Assets {
    --
    +{static} of(String[]): Assets
    +{static} edit(Asset, Asset): Assets
}
}

Assets "1" -down-> "*" Asset

Person -right->"1" Assets

@enduml
