@startuml
!include style.puml
skinparam ArrowFontStyle plain

box UI UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
participant ":RecordedCommandExecutor" as RecordedCommandExecutor UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandHistory" as CommandHistory LOGIC_COLOR
end box

'box JavaFX JAVAFX_COLOR_T1
participant ":TextField" as TextField JAVAFX_COLOR
'end box

-> CommandBox : handleKeyPressed(event)
activate CommandBox

CommandBox -> RecordedCommandExecutor : getPreviousCommandText()
activate RecordedCommandExecutor

RecordedCommandExecutor -> LogicManager : getPreviousCommandText()
activate LogicManager

LogicManager -> CommandHistory : getPrevious()
activate CommandHistory

CommandHistory --> LogicManager : commandText
deactivate CommandHistory

LogicManager --> RecordedCommandExecutor : commandText
deactivate LogicManager

RecordedCommandExecutor --> CommandBox : commandText
deactivate RecordedCommandExecutor

CommandBox -> TextField : setText(commandText)
activate TextField

TextField --> CommandBox
deactivate TextField

<-- CommandBox
deactivate CommandBox

@enduml
