@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "<<class>>\nCommandType" as CommandTypeClass LOGIC_COLOR
participant "type:CommandType" as CommandType LOGIC_COLOR
participant "<<class>>\nDeleteCommand" as DeleteCommandClass LOGIC_COLOR
participant "command:DeleteCommand" as DeleteCommand LOGIC_COLOR
end box

[-> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

AddressBookParser -> CommandTypeClass : valueOf("DELETE")
activate CommandTypeClass

create CommandType
CommandTypeClass -> CommandType
activate CommandType

CommandType -> CommandTypeClass : type
deactivate CommandType

CommandTypeClass -> AddressBookParser : type
deactivate CommandTypeClass

AddressBookParser -> CommandType : createCommand(" 1")
activate CommandType

CommandType -> DeleteCommandClass : of(" 1")
activate DeleteCommandClass

create DeleteCommand
DeleteCommandClass -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandClass : command
deactivate DeleteCommand

DeleteCommandClass --> CommandType : command
deactivate DeleteCommandClass

CommandType --> AddressBookParser : command
deactivate CommandType

[<-- AddressBookParser : command
deactivate AddressBookParser

@enduml
