@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant "<<class>>\nFindCommand" as FindCommandClass LOGIC_COLOR
participant "command:FindCommand" as FindCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "predicate:PersonMatchesQueryPredicate" as PersonMatchesQueryPredicate MODEL_COLOR
end box

-> FindCommandClass : of(" David")
activate FindCommandClass

create PersonMatchesQueryPredicate
FindCommandClass -> PersonMatchesQueryPredicate : PersonMatchesQueryPredicate("David")
activate PersonMatchesQueryPredicate

PersonMatchesQueryPredicate --> FindCommandClass : predicate
deactivate PersonMatchesQueryPredicate

create FindCommand
FindCommandClass -> FindCommand : FindCommand(predicate)
activate FindCommand

FindCommand --> FindCommandClass : command
deactivate FindCommand

<-- FindCommandClass : command
deactivate FindCommandClass

@enduml
